site_name: Parallelizer
site_url: https://Artzified.github.io/parallelizer/
nav:
  - Home: index.md
  - Guides:
    - Getting Started: guides/getting-started.md
    - Installation: guides/installation.md
  - References:
    - Parallelizer: api/index.md
    - Job Scheduler: api/job-scheduler.md
    - Types: api/types.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    edit: material/pencil
    view: material/eye
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.tooltips
    - header.autohide
  palette:
    scheme: slate
    primary: indigo